### PR TITLE
Fix hasPaid

### PR DESCRIPTION
**Pull request by destruc7i0n**
Do a simple test for if there is an error from the string, what do you think @yrsegal ? (The old API went down D:)

### CODE REVIEW

**Comment by yrsegal** [comment]
the CI appears to be complaining about the fact that... the test isn't working, but the actual code is. >.>

**Comment by yrsegal** [comment]
also, don't use urlopen. Use curl, based on the newest system, to fetch all urls.

**Comment by ttofis** [comment]
Why not try to get a uuid. If it fails, just say that the man doesn't have a paid account. Or if that doesn't work something from here might work https://sessionserver.mojang.com/session/minecraft/profile/<uuid>

**Comment by ttofis** [comment]
Oh, just saw the code again. You have already done this.

**Comment by destruc7i0n** [comment]
I'll make an edit.

**Comment by destruc7i0n** [comment]
Wait, doesn't "urlopen" go to curl? I can change it if you like but I don't deem it necessary.

**Comment by ttofis** [comment]
Not automatically. Just follow the other places that use curl and use curl too. For the sake of version agnostic.

**Comment by yrsegal** [comment]
curl is a lambda function I added, that wraps urlopen for version safety.

**Pull request closed without merging**
