### PR TITLE
Tweaked it to work with Python 2 and 3

### PR DESCRIPTION
**Pull request by ttofis**
And fixed the annoying fake commit at the end!

### CODE REVIEW

**Comment by ttofis** [comment]
Removed one if statement. Now, it should run a bit faster. Reason for two commits: Weird conflict issue. No idea why.

**Comment by yrsegal** [comment]
AAAAAAAAA why are you importing on runtime that's the opposite of what I said to do

**Comment by ttofis** [comment]
Is it now like you said me to do?

**Comment by yrsegal** [comment]
200e95f9d7adb4c8886e188eac4d1ee40a50a971

**Comment by ttofis** [comment]
Oh. I didn't know this method. I am sorry.

**Comment by ttofis** [comment]
At least you could tell me how do you like it and just merge. Even squash the commits so it shows as one. But I don't know... It seems that you work on the project and it isn't dead for 6 months. At least, pypixel is getting updated. Which is something on it's own.

**Comment by yrsegal** [comment]
The thing is that squashing the commits you have would have still required
a fixit commit. Doing a single commit made more sense.

This is d70's pet project, not mine. I just made it better. If you want to
complain about a dead API, do it to him.

**Comment by ttofis** [comment]
I didn't complaint that the api is dead. Let's just end this conversation here. It doesn't matter. The thing that matters is that with work by you and me we made the api better. That's what matters. The community working on making something better.

**Comment by ttofis** [comment]
And also I am sorry if I made it look that I was angry. Totally not.

**Pull request closed without merging**
